name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}  # cancel previous runs on the same branch
  cancel-in-progress: true  # cancel outdated runs

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.11
        environment-file: environment.yaml
        activate-environment: tiw-sst-forecasting
        
    - name: Build documentation
      shell: bash -l {0}
      run: |
        cd docs
        make html
        
    - name: Check documentation build
      shell: bash -l {0}
      run: |
        # Check that key documentation files were created
        ls -la docs/build/html/
        test -f docs/build/html/index.html
        test -f docs/build/html/modules.html
        echo "✓ Documentation built successfully"
        
    - name: Setup Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/build/html
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      id: deployment
      uses: actions/deploy-pages@v4