name: Auto-Format Code

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Install formatting tools
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8
        
    - name: Format Python files with black
      run: |
        black . --extend-exclude="notebooks/"
        
    - name: Sort imports with isort
      run: |
        isort . --skip-glob="notebooks/*"
        
    - name: Check for basic syntax errors
      run: |
        flake8 . --select=E9,F63,F7,F82 --exclude=notebooks/ --show-source --statistics
        
    - name: Commit formatting changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if ! git diff --cached --quiet; then
          git commit -m "Auto-format Python code with black and isort

🤖 Generated with [Claude Code](https://claude.ai/code)"
          git push
        else
          echo "No formatting changes needed"
        fi